Repository moodle/devdocs, pull requests merged in 2022-04, with the labels that each got.

#10 Add linting and style checks
  .env.default
  .github/workflows/lint-pr.yml
  .github/workflows/markdown-lint.yml
  .github/workflows/new-issues.yml
  .gitignore
  .markdownlint.yaml
  README.md
  docs/apis.md
  docs/apis/access.md
  docs/gettingstarted/quickstart.md
  docs/gettingstarted/requirements.md
  docs/gettingstarted/setup.md
  docs/guides/javascript/index.md
  docs/guides/moodleapp/index.md
  docs/intro.md
  docs/release-notes.md
  docs/tools/mdk.md
  general/community/channels.md
  general/community/intro.md
  general/community/meetings.md
  general/community/meetings/202202.md
  general/community/research.md
  general/community/roadmap.md
  general/development/policies/codingstyle/index.md
  general/development/policies/component-communication/index.md
  general/development/process.md
  general/development/process/peer-review.md
  general/development/tracker.md
  general/development/tracker/tips/index.md
  package.json
  yarn.lock
Labels: migration

#35 [system] Keep track of migrated docs and warn on use
  docs/apis.md
  docs/guides/moodleapp/coding-style.md
  general/development/process.md
  migratedPages.js
  src/remark/legacyDocLinks.js
Labels: enhancement, migration

#51 Introduce pre-commit hooks to lint and check more content
  .eslintrc.js
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .lintstagedrc.json
  README.md
  academyCourses.js
  config/footer.js
  config/imageZoom.js
  config/navbar.js
  config/prism.js
  cspell.config.js
  docs/apis.md
  docs/apis/access.md
  docs/apis/plugintypes/mod.md
  docs/gettingstarted/requirements.md
  docs/gettingstarted/setup.md
  docs/guides/javascript/_examples/promises/getModal.js
  docs/guides/javascript/index.md
  docs/intro.md
  docusaurus.config.js
  general/community/roadmap.md
  general/development/policies/codingstyle/index.md
  general/development/process.md
  general/development/process/integration-review.md
  general/development/process/peer-review.md
  general/development/process/testing/integrated-issues.md
  general/development/tracker/tips/index.md
  migratedPages.js
  package.json
  project-words.txt
  sidebars/docs.js
  sidebars/general.js
  src/academyCourses.js
  src/components/AcademyLink.js
  yarn.lock
Labels: enhancement, repo, tooling

#53 [docs] Migrate 4.0.0 release notes
  cspell.config.js
  docs/release-notes.md
  migratedPages.js
Labels: documentation, migration

#50 [repo] Add Contributions guide
  .github/workflows/label-new-issues.yml
  .nvmrc
  CONTRIBUTING.md
  COPYING.txt
  config/footer.js
  docs/intro.md
  general/community/code-of-conduct.md
  general/documentation/code-of-conduct.md
  general/documentation/contributing.md
  general/documentation/index.md
  general/documentation/style-guides.md
  project-words.txt
  sidebars/general.js
Labels: repo

#59 [docs] api/files: Migrate file API docs
  docs/apis.md
  docs/apis/files/browsing.md
  docs/apis/files/index.md
  docs/apis/files/internals.md
  docs/apis/plugintypes/_category_.yml
  docs/apis/plugintypes/mod.md
  migratedPages.js
  project-words.txt
Labels: documentation, migration

#62 [repo] Automate migration and update of page obseletion
  .github/workflows/update-wikimedia.yml
  data/migratedPages.yml
  data/obsoletePages.json
  general/community/research.md
  migratedPages.js
  package.json
  scripts/updateMigratedPages.js
  yarn.lock
Labels: migration, repo, tooling

#65 [repo] The update-wikimedia script should only run on our repo
  .github/workflows/update-wikimedia.yml
Labels: repo

#66 [docs] policies/accessibility: Migrate Accessibility docs
  .markdownlint.yaml
  data/migratedPages.yml
  general/development/policies/accessibility.md
  general/development/policies/codingstyle/index.md
  project-words.txt
Labels: documentation, migration

#72 [docs] Remove references to contact Helen in QA
  general/development/process/testing/qa.md
Labels: documentation

#71 [docs] process/triage: Migrate Bug triage
  data/migratedPages.yml
  general/development/process.md
  general/development/process/_files/cannedresponses.png
  general/development/process/triage.md
  general/development/tracker/tips/index.md
  general/development/tracker/tips/savefilter1.png
  general/development/tracker/tips/savefilter2.png
  general/development/tracker/tips/savefilter3.jpeg
  general/development/tracker/tips/savefilter3.png
  sidebars/general.js
Labels: documentation, migration
