Repository moodle/devdocs, pull requests merged in 2024-04, with the labels that each got.

#949 Add information about Mermaid to contributing.md
  general/documentation/contributing.md
Labels: needs-triage

#886 Documentation for \core\clock interface
  docs/apis/core/clock/index.md
  docs/devupdate.md
Labels: blocked-by-tracker

#951 [docs] Document removal of blocking task support - MDL-67667
  docs/apis/subsystems/task/index.md
  docs/devupdate.md
Labels: blocked-by-tracker

#979 4.4 QA cycle credits
  general/community/credits/testing.md
Labels: needs-triage

#981 Link to 4.4 QA cycle
  general/development/process/testing/qa.md
Labels: needs-triage

#973 Add new Task APIs documentation
  docs/apis/subsystems/task/adhoc.md
  docs/devupdate.md
Labels: waiting-for-feedback

#972 Add dropzone documentation
  docs/devupdate.md
  docs/guides/javascript/index.md
Labels: waiting-for-feedback

#988 reorder testing credits list showing recent release first
  general/community/credits/testing.md
Labels: needs-triage

#980 4.5 dates
  data/versions.json
  src/utils/SupportedReleases.ts
  static/schema/versions.json
Labels: waiting-for-feedback
