Repository moodle/devdocs, pull requests merged in 2025-03, with the labels that each got.

#1240 MDL-81015: Remove info docs for async
  docs/apis/subsystems/sms/index.md
Labels: blocked-by-tracker

#1280 MDL-83541 Add qtype restore code documentation
  docs/apis/plugintypes/qtype/index.md
  docs/apis/plugintypes/qtype/restore.md
Labels: blocked-by-tracker

#1302 Final deprecation policy update to keep method signature
  general/development/policies/deprecation/index.md
Labels: needs-triage

#1295 [Docs] Adding new Writing for Accessibility page
  general/contentguidelines/01-productwriting/_files/course_index.png
  general/contentguidelines/01-productwriting/_files/empty_state.png
  general/contentguidelines/01-productwriting/writingforaccessibility.md
Labels: waiting-for-feedback
