Repository moodle/devdocs, pull requests merged in 2025-01, with the labels that each got.

#1210 [docs] Describe the new subplugintypes object (MDL-83705)
  docs/devupdate.md
  general/development/tools/metadata/index.md
Labels: blocked-by-tracker

#1223 Fix typos in fixups.md
  general/development/abc/fixups.md
Labels: needs-triage

#1239 MDL-82767 course format state updates
  docs/apis/plugintypes/format/index.md
Labels: blocked-by-tracker

#1221 Update AI Provider plugin documentation for provider instances.
  docs/apis/plugintypes/ai/provider.md
Labels: blocked-by-tracker

#1199 Add question bank filter API guide
  docs/apis/plugintypes/qbank/filters.md
  docs/apis/plugintypes/qbank/index.md
  versioned_docs/version-4.3/apis/plugintypes/qbank/filters.md
  versioned_docs/version-4.3/apis/plugintypes/qbank/index.md
  versioned_docs/version-4.4/apis/plugintypes/qbank/filters.md
  versioned_docs/version-4.4/apis/plugintypes/qbank/index.md
  versioned_docs/version-4.5/apis/plugintypes/qbank/filters.md
  versioned_docs/version-4.5/apis/plugintypes/qbank/index.md
Labels: waiting-for-feedback
